name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ dbc-gen ]
  pull_request:
    branches: [ dbc-gen ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: parser_exe.py

    - uses: actions/upload-artifact@v2
      with:
        name: parser-exe
        path: src/dist/windows # or path/to/artifact