name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ dbc-gen ]
  pull_request:
    branches: [ dbc-gen ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Replace '3.x' with your Python version
      
    - uses: actions/checkout@v2
    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: ./

    - uses: actions/upload-artifact@v2
      with:
        name: parser-exe
        path: ./dist/windows # or path/to/artifact