name: Package exe with PyInstaller - Windows

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Replace '3.x' with your Python version
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: run pyinstaller
      run: |
        pyinstaller ./parser_exe.py
    - name: test
      run: |
        ls
        cd build
        ls
        cd parser_exe
        ls
        cd parser_exe
        ls

    - uses: actions/upload-artifact@v2
      with:
        name: parser-exe
        path: |
          ./dist/windows/parser_exe/*.exe
          ./build/parser_exe/parser_exe/*
