name: Package exe with PyInstaller - Windows

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Replace '3.x' with your Python version
      
    - name: run pyinstaller
      run:
        pyinstaller ./parser_exe.py

    - uses: actions/upload-artifact@v2
      with:
        name: parser-exe
        path: ./dist/windows/parser_exe/*.exe # or path/to/artifact
